version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: 'npm version check'
          command: npm --version
      - run:
          name: 'Node.js version check'
          command: node --version
      - checkout
      - run:
          name: 'Install Firebase CLI tools'
          command: npm install --save-dev firebase-tools
      - run:
          name: 'Deploy to Hosting'
          command: ./node_modules/.bin/firebase deploy --token="$FIREBASE_TOKEN"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master